apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: small-change-fse1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: akashl21/small-change-angular-fse1:latest
        ports:
        - containerPort: 4200
      imagePullSecrets:
      - name: my-registry-secret      
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app
  namespace: small-change-fse1
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
